version: "2"

linters:
  default: none
  enable:
    - loglint

linters-settings:
  custom:
    loglint:
      type: module
      description: "Static analysis tool for detecting style violations and sensitive data leaks in Go log messages."
      original-url: "github.com/Sene4ka/loglint"
      settings:
        allowed_special_symbols: "! . ,"
        sensitive_keywords:
          - word1
          - word2
        rules:
          rule_lowercase: true
          rule_english: true
          rule_symbols: true
          rule_sensitive: true