version: "2"

linters:
  default: none # disable default linters, only for test purposes
  enable:
    - loglint

linters-settings:
  custom:
    loglint:
      type: "module"
      description: "Reports wrong log function usages"
      original-url: "github.com/Sene4ka/log-linter"
      settings:
        allowed_special_symbols: '! . ,' # default ': _ - = %'
        sensitive_keywords: 'word1,word2' # default 'key,password,secret,auth,token'
        rules:
          rule-lowercase: "false" # can be omitted (default "true")
          rule-english: "false" # can be omitted (default "true")
          rule-symbols: "false" # can be omitted (default "true")
          rule-sensitive: "false" # can be omitted (default "true")